export const GET_USER_FROM_STORAGE = 'GET_USER_FROM_STORAGE';
export const SET_USER = 'SET_USER';
export const SET_WHICH_MODAL_TO_OPEN = 'SET_WHICH_MODAL_TO_OPEN';

export const ADD_TRACK = 'ADD_TRACK';
export const SET_MODAL_STATE = 'SET_MODAL_STATE';
export const EDIT_TRACK_BY_ID = 'EDIT_TRACK_BY_ID';
export const DELETE_TRACK_BY_ID = 'DELETE_TRACK_BY_ID';

export const REMOVE_EVERYTHING = 'REMOVE_EVERYTHING';
